spring:
  app:
    PolygonClient:
      apiKey: NHk6To6V7yJoxZt6175WfWN301IGCa36

  profiles:
    active: dev #dev #prod (development / production)
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser

  application:
    name: stock
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=stock
    username: postgres
    password: tic-tel
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto:auto
    show-sql: true
    repositories:
      enable-default-transactions: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        connection.provider_disables_autocommit: true
        connection:
          provider_disables_autocommit: true
          autocommit: false

server:
  port: 8080
  error:
    include-stacktrace: always
  session:
    timeout: 30m
    cookie:
      http-only: true
      secure: false
logging:
  level:
    org.springframework.transaction: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.engine.transaction.internal.TransactionImpl: TRACE
